#!/usr/bin/env node

/**
 * secure-cartography-js — STT Port Map Generator
 *
 * Converts a Secure Cartography topology JSON file (map.json) into
 * an snmpproxy.yaml port map for STT-SNMP tunnel discovery.
 *
 * Input:  Any SC map.json (same format across all SC versions)
 * Output: snmpproxy.yaml with localhost port mappings
 *
 * Usage:
 *   node src/stt-gen.js map.json
 *   node src/stt-gen.js map.json -o snmpproxy.yaml
 *   node src/stt-gen.js map.json --start-port 20001
 *   node src/stt-gen.js map.json --ssh-host bastion.example.com --ssh-user admin
 *
 * The generated file can be used with:
 *   node src/sc-js.js crawl <seed> -c lab --stt-file snmpproxy.yaml
 */

'use strict';

const fs = require('fs');
const path = require('path');

// =========================================================================
// Defaults
// =========================================================================

const DEFAULTS = {
  startPort: 10001,
  bindAddress: '127.0.0.1',
  remotePort: 161,
  requestTimeout: 10,
  keepaliveInterval: 30,
  sshHost: 'localhost',
  sshPort: 22,
  sshUser: process.env.USER || 'user',
  sshKeyFile: '~/.ssh/id_rsa',
  remotePython: 'python3',
  remoteAgent: '/opt/sttsnmp/snmpproxy_remote.py',
};


// =========================================================================
// Parse topology JSON
// =========================================================================

/**
 * Extract devices from SC topology map.json.
 * Handles the standard SC format:
 *   { "device-name": { "node_details": { "ip": "...", "platform": "..." }, "peers": {...} } }
 *
 * @param {object} topology - Parsed map.json
 * @returns {Array<{name: string, ip: string, platform: string}>}
 */
function extractDevices(topology) {
  const devices = [];

  for (const [name, node] of Object.entries(topology)) {
    const details = node.node_details || node.nodeDetails || {};
    const ip = details.ip || '';

    if (!ip) continue; // Skip devices with no IP

    devices.push({
      name,
      ip,
      platform: details.platform || 'Unknown',
    });
  }

  // Sort by name for stable port assignment
  devices.sort((a, b) => a.name.localeCompare(b.name));

  return devices;
}


// =========================================================================
// Generate YAML
// =========================================================================

/**
 * Generate snmpproxy.yaml content.
 *
 * @param {Array<{name: string, ip: string, platform: string}>} devices
 * @param {object} opts
 * @returns {string} YAML content
 */
function generateYaml(devices, opts = {}) {
  const startPort = opts.startPort || DEFAULTS.startPort;
  const bindAddress = opts.bindAddress || DEFAULTS.bindAddress;
  const remotePort = opts.remotePort || DEFAULTS.remotePort;
  const requestTimeout = opts.requestTimeout || DEFAULTS.requestTimeout;
  const keepaliveInterval = opts.keepaliveInterval || DEFAULTS.keepaliveInterval;
  const sshHost = opts.sshHost || DEFAULTS.sshHost;
  const sshPort = opts.sshPort || DEFAULTS.sshPort;
  const sshUser = opts.sshUser || DEFAULTS.sshUser;
  const sshKeyFile = opts.sshKeyFile || DEFAULTS.sshKeyFile;
  const remotePython = opts.remotePython || DEFAULTS.remotePython;
  const remoteAgent = opts.remoteAgent || DEFAULTS.remoteAgent;

  const lines = [];

  // Header comment with port map summary
  lines.push('# snmpproxy.yaml — Generated by secure-cartography-js');
  lines.push(`# Generated: ${new Date().toISOString()}`);
  lines.push(`# Devices: ${devices.length}`);
  lines.push('#');
  lines.push('# Port map:');

  const nameWidth = Math.max(...devices.map(d => d.name.length), 8);
  const ipWidth = Math.max(...devices.map(d => d.ip.length), 12);

  for (let i = 0; i < devices.length; i++) {
    const port = startPort + i;
    const d = devices[i];
    lines.push(
      `#   ${String(port).padEnd(7)}${d.name.padEnd(nameWidth + 2)}${d.ip.padEnd(ipWidth + 3)}${d.platform.split('\n')[0].trim().slice(0, 60)}`
    );
  }

  lines.push('');

  // SSH section
  lines.push('ssh:');
  lines.push(`  host: ${sshHost}`);
  lines.push(`  port: ${sshPort}`);
  lines.push(`  username: ${sshUser}`);
  lines.push(`  key_file: ${sshKeyFile}`);
  lines.push(`  remote_python: ${remotePython}`);
  lines.push(`  remote_agent: ${remoteAgent}`);
  lines.push('');

  // Global settings
  lines.push(`bind_address: ${bindAddress}`);
  lines.push(`request_timeout: ${requestTimeout}`);
  lines.push(`keepalive_interval: ${keepaliveInterval}`);
  lines.push('');

  // Targets
  lines.push('targets:');

  for (let i = 0; i < devices.length; i++) {
    const port = startPort + i;
    const d = devices[i];

    if (i > 0) lines.push('');
    lines.push(`  - local_port: ${port}`);
    lines.push(`    remote_host: ${d.ip}`);
    lines.push(`    remote_port: ${remotePort}`);
    lines.push(`    label: ${d.name}`);
  }

  lines.push('');

  return lines.join('\n');
}


/**
 * Generate a lookup map: device IP → localhost:port
 * This is what the --stt-file flag uses at runtime.
 *
 * @param {string} yamlPath - Path to snmpproxy.yaml
 * @returns {Map<string, {host: string, port: number, label: string}>}
 */
function loadSttLookup(yamlPath) {
  const content = fs.readFileSync(yamlPath, 'utf-8');
  const lookup = new Map();

  // Simple YAML parser for the targets section — avoids a yaml dependency
  let inTargets = false;
  let current = {};

  for (const line of content.split('\n')) {
    const trimmed = line.trim();

    if (trimmed === 'targets:') {
      inTargets = true;
      continue;
    }

    if (!inTargets) continue;

    // New target entry
    if (trimmed.startsWith('- local_port:')) {
      // Save previous if complete
      if (current.remoteHost && current.localPort) {
        lookup.set(current.remoteHost, {
          host: '127.0.0.1',
          port: current.localPort,
          label: current.label || '',
        });
      }
      current = {};
      current.localPort = parseInt(trimmed.split(':')[1].trim(), 10);
      continue;
    }

    if (trimmed.startsWith('remote_host:')) {
      current.remoteHost = trimmed.split(':').slice(1).join(':').trim();
    } else if (trimmed.startsWith('remote_port:')) {
      current.remotePort = parseInt(trimmed.split(':')[1].trim(), 10);
    } else if (trimmed.startsWith('label:')) {
      current.label = trimmed.split(':').slice(1).join(':').trim();
    }

    // Non-indented line after targets means we left the section
    if (inTargets && !line.startsWith(' ') && !line.startsWith('\t') && trimmed && !trimmed.startsWith('#') && !trimmed.startsWith('-')) {
      break;
    }
  }

  // Save last entry
  if (current.remoteHost && current.localPort) {
    lookup.set(current.remoteHost, {
      host: '127.0.0.1',
      port: current.localPort,
      label: current.label || '',
    });
  }

  return lookup;
}


// =========================================================================
// CLI
// =========================================================================

function main() {
  const args = process.argv.slice(2);

  if (args.length === 0 || args.includes('--help') || args.includes('-h')) {
    console.log(`
Usage: node src/stt-gen.js <map.json> [options]

Convert a Secure Cartography topology file to an STT-SNMP proxy port map.

Options:
  -o, --output <file>       Output file (default: snmpproxy.yaml)
  --start-port <port>       First local port (default: 10001)
  --ssh-host <host>         SSH tunnel host (default: localhost)
  --ssh-port <port>         SSH tunnel port (default: 22)
  --ssh-user <user>         SSH username (default: $USER)
  --ssh-key <path>          SSH key file (default: ~/.ssh/id_rsa)
  --remote-python <path>    Remote Python path
  --remote-agent <path>     Remote agent script path
  --bind <address>          Bind address (default: 127.0.0.1)

Examples:
  node src/stt-gen.js output/map.json
  node src/stt-gen.js output/map.json -o lab-proxy.yaml --start-port 20001
  node src/stt-gen.js output/map.json --ssh-host bastion.lab --ssh-user admin
`);
    process.exit(0);
  }

  // Parse args
  const inputFile = args[0];
  let outputFile = 'snmpproxy.yaml';
  const opts = {};

  for (let i = 1; i < args.length; i++) {
    switch (args[i]) {
      case '-o': case '--output':
        outputFile = args[++i]; break;
      case '--start-port':
        opts.startPort = parseInt(args[++i], 10); break;
      case '--ssh-host':
        opts.sshHost = args[++i]; break;
      case '--ssh-port':
        opts.sshPort = parseInt(args[++i], 10); break;
      case '--ssh-user':
        opts.sshUser = args[++i]; break;
      case '--ssh-key':
        opts.sshKeyFile = args[++i]; break;
      case '--remote-python':
        opts.remotePython = args[++i]; break;
      case '--remote-agent':
        opts.remoteAgent = args[++i]; break;
      case '--bind':
        opts.bindAddress = args[++i]; break;
    }
  }

  // Read topology
  if (!fs.existsSync(inputFile)) {
    console.error(`Error: File not found: ${inputFile}`);
    process.exit(1);
  }

  let topology;
  try {
    topology = JSON.parse(fs.readFileSync(inputFile, 'utf-8'));
  } catch (e) {
    console.error(`Error: Invalid JSON in ${inputFile}: ${e.message}`);
    process.exit(1);
  }

  // Extract devices
  const devices = extractDevices(topology);

  if (devices.length === 0) {
    console.error('Error: No devices with IP addresses found in topology file.');
    process.exit(1);
  }

  // Generate and write
  const yaml = generateYaml(devices, opts);
  fs.writeFileSync(outputFile, yaml, 'utf-8');

  console.log(`Generated ${outputFile} with ${devices.length} device mappings`);
  console.log(`Port range: ${opts.startPort || DEFAULTS.startPort}–${(opts.startPort || DEFAULTS.startPort) + devices.length - 1}`);
}


// =========================================================================
// Exports (for use by engine.js --stt-file)
// =========================================================================

module.exports = {
  extractDevices,
  generateYaml,
  loadSttLookup,
};


// Run CLI if executed directly
if (require.main === module) {
  main();
}